### ISSUE TITLE
CRAFT cannot detect input files

### ISSUE THREAD

**Issue by MSajek** [annadalmolin/CRAFT#1]
Hi,
CRAFT looks like very convenient tool for circRNA analysis. However I am not able to run even test example because of dome errors. I run the following command:
`sudo docker run -u `id -u` -it -v $(pwd):/data annadalmolin/craft:v1.0`
After running command I have the following errors:
```
cat: /data/path_files.txt: No such file or directory
cat: /data/path_files.txt: No such file or directory
cat: /data/list_backsplice.txt: No such file or directory
```
Input files are the copies of your examples.
My working directory is:
`/media/marcin/data/lymphoma_circs/test`
and structure of the files is:
```
.
└── data
    ├── input
    │   ├── backsplice_gene_name.txt
    │   ├── est.fa
    │   ├── est.fa.gz.md5
    │   ├── hg38.2bit
    │   ├── hg38.agp
    │   ├── hg38.chromAlias.bb
    │   ├── hg38.chromAlias.txt
    │   ├── hg38.chromAlias.txt.0
    │   ├── hg38.chromFaMasked.tar
    │   ├── hg38.chromFa.tar
    │   ├── hg38.chrom.sizes
    │   ├── hg38.fa
    │   ├── hg38.fa.align
    │   ├── hg38.fa.masked
    │   ├── hg38.fa.out
    │   ├── hg38.gc5Base.bw
    │   ├── hg38.gc5Base.wib
    │   ├── hg38.gc5Base.wig
    │   ├── hg38.gc5Base.wigVarStep
    │   ├── hg38.trf.bed
    │   ├── Homo_sapiens.GRCh38.104.gtf
    │   ├── Homo_sapiens.GRCh38.dna.primary_assembly.fa
    │   ├── md5sum.txt
    │   ├── mrna.fa
    │   ├── mrna.fa.gz.md5
    │   ├── README.txt
    │   ├── refMrna.fa
    │   ├── refMrna.fa.gz.md5
    │   ├── upstream1000.fa
    │   ├── upstream1000.fa.gz.md5
    │   ├── upstream2000.fa
    │   ├── upstream2000.fa.gz.md5
    │   ├── upstream5000.fa
    │   ├── upstream5000.fa.gz.md5
    │   ├── xenoMrna.fa
    │   ├── xenoMrna.fa.gz.md5
    │   ├── xenoRefMrna.fa
    │   └── xenoRefMrna.fa.gz.md5
    ├── list_backsplice.txt
    ├── params.txt
    └── path_files.txt
```

Thanks for any help.

Marcin

**Comment by annadalmolin** [comment]
Hi MSajek, thank you for using CRAFT.

From what I see, CRAFT is not able to detect input files, because there is something wrong in the project directory structure.
Do you have a directory "data" into the "test" directory?

Ps: keep attention to the backtick when you run the docker command:
sudo docker run -u `id -u` -it -v $(pwd):/data annadalmolin/craft:v1.0

Let me know,
Anna

**Comment by MSajek** [comment]
Hi Anna,
Yes, I have directory 'data' within the 'test'  directory, as you can see above. Dir 'data' contains the following files 'list_backsplice.txt', 'params.txt','path_files.txt'.

**Comment by annadalmolin** [comment]
This is precisely the problem.
You must NOT have another "data" directory into the "test" directory, because "test" IS your "data" directory (this is how docker works).
So, move "list_backsplice.txt", "params.txt", "path_files.txt" and the "input" directory inside "test", remove "data" and then run the CRAFT command from "test".
Now it should run with any problem.

Anna

**Comment by MSajek** [comment]
Now it works, thanks a lot!

**Comment by AnaTrobec** [comment]
Hi,
I have a similar problem and although I checked everything you already said, I have troubles running an analysis. I prepared all the necessary files for analysis, directory structure should be right, I copied the command: `docker` `run` `-it` `-v` `$(pwd):/data` `annadalmolin/craft:v1.0`  to command prompt, where instead of $(pwd) I put a path to working directory, but then I get an error: 

_Quitting_ from lines 90-153 (functional_predictions_all_circRNAs.Rmd) 
Error in read.table(file_parameters, header = F) : 
no lines available in input
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read.table
In addition: Warning message:
package(s) not installed when version(s) same as current; use `force = TRUE` to
re-install: 'grid' 
Execution _halted_

Should I run it in Linux or directly in Docker?
I'm new to bioinformatics, so I might be making some basic mistakes. I find your analysis process so cool though, I would really like to see make it work :)

**Comment by SREERAMIISERB** [comment]
> This is precisely the problem. You must NOT have another "data" directory into the "test" directory, because "test" IS your "data" directory (this is how docker works). So, move "list_backsplice.txt", "params.txt", "path_files.txt" and the "input" directory inside "test", remove "data" and then run the CRAFT command from "test". Now it should run with any problem.
> 
> Anna

Madam Im getting something different i mean im getting the directories but theres no content in those dirrectory with different folders present in it
